IAB Ran tutorial
open-5g/openrangym pull request #11
Opened 2023-04-22 12:30 UTC by gabri94

2023-04-25 01:47 UTC, mychele requested changes
Thanks for writing this!

2023-04-25 01:47 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +In the remaining of this tutorial, we assume users started an interactive reservation on Colosseum with at least 4 IAB RAN nodes (`oai-iab-ran` or `oai-iab-ran-stable` image), one OAI IAB-aware core
What is the difference between these two images?

2023-04-25 01:47 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +In the remaining of this tutorial, we assume users started an interactive reservation on Colosseum with at least 4 IAB RAN nodes (`oai-iab-ran` or `oai-iab-ran-stable` image), one OAI IAB-aware core
Can we keep one?

2023-04-25 01:47 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +Once the reservation is ready, iab-manager can be used to interact with the different components. First of all, create a `.env` in the main folder containing your colosseum credentials in the format:
main folder of what? Where should iab-manager go?

2023-04-25 01:47 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +Then, you must configure `iab-manager` through the `config.yml` configuration file. Create the file with the following content:
Check `iab-manager` vs iab-manager

2023-04-25 01:47 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +It's also possible to start the network manually by starting first the iab-donor, then the iab-relays and finally the UE: `donor 0 start`, `iab_node start 12`, `iab_node start 34`, `iab_node start 56
```suggestion
It is also possible to start the network manually by starting first the iab-donor, then the iab-relays and finally the UE: `donor 0 start`, `iab_node start 12`, `iab_node start 34`, `iab_node start 56`, `iab_node start 78`, `ue 9 start`
```

2023-04-25 01:47 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +It's also possible to start the network manually by starting first the iab-donor, then the iab-relays and finally the UE: `donor 0 start`, `iab_node start 12`, `iab_node start 34`, `iab_node start 56
Also, what are these numbers?

2023-04-25 01:47 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +
```suggestion
To be updated.

```

2023-04-25 01:47 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +
```suggestion
To be updated.

```

2023-04-25 01:47 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +### Non-RT RIC Setup
```suggestion
### Non-RT RIC Setup
To be updated.

```

2023-04-25 10:17 UTC, gabri94 commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +In the remaining of this tutorial, we assume users started an interactive reservation on Colosseum with at least 4 IAB RAN nodes (`oai-iab-ran` or `oai-iab-ran-stable` image), one OAI IAB-aware core
I'd have a `stable` image that's kept at commit that we know it works and we rarely updates after testing it thorougly, and a `develop` image that's more often (ideally continuously) updated to be on top of develop.

2023-04-25 10:18 UTC, gabri94 commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +Once the reservation is ready, iab-manager can be used to interact with the different components. First of all, create a `.env` in the main folder containing your colosseum credentials in the format:
In the main folder of iab-manager, which, as stated in L18 goes either on your laptop or on the core node.

2023-04-25 10:19 UTC, gabri94 commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +It's also possible to start the network manually by starting first the iab-donor, then the iab-relays and finally the UE: `donor 0 start`, `iab_node start 12`, `iab_node start 34`, `iab_node start 56
Each node in the topology.graphml file has an ID that is used to identify it. I didn't wanted to go down in the details of how iab-manager works as I want to keep the tutorial simple.

2023-04-25 12:47 UTC, mychele requested changes

2023-04-25 12:47 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +In the remaining of this tutorial, we assume users started an interactive reservation on Colosseum with at least 4 IAB RAN nodes (`oai-iab-ran` or `oai-iab-ran-stable` image), one OAI IAB-aware core
Ok but let's point the users to the stable image

2023-04-25 12:47 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +Once the reservation is ready, iab-manager can be used to interact with the different components. First of all, create a `.env` in the main folder containing your colosseum credentials in the format:
Please clarify also here, thanks!

2023-04-25 14:07 UTC, mychele requested changes
There's also @leonardobonati comment to be addressed

2023-04-25 14:07 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +Then enter the directory and create a `.env` in the main folder containing your colosseum credentials in the format:
```suggestion
Then enter the directory and create a `.env` in the main folder containing your Colosseum credentials in the format:
```

2023-04-25 14:07 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +It is also possible to start the network manually by starting first the iab-donor, then the iab-relays and finally the UE: `donor 0 start`, `iab_node start 12`, `iab_node start 34`, `iab_node start 5
I think there was a comment on "what are these numbers", but I don't see it (even resolved), so I'll write it again: what are these numbers? How can a reader of this tutorial interpret (and in case) change them? Do they need to change them or not?

2023-04-25 14:53 UTC, gabri94 commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +It is also possible to start the network manually by starting first the iab-donor, then the iab-relays and finally the UE: `donor 0 start`, `iab_node start 12`, `iab_node start 34`, `iab_node start 5
I answered it, but it got deleted by gh.
Those numbers are the ids of the nodes in the topology file (`toy1.graphml `). There's a dynamical matching between SRNs  (colosseum), Radio IDs (MCHEM) and Topology IDs that is automatically done by iab-manager.However, I'm uncertain how deep I should go into the details of this and in general of the mechanics of iab-manager into this tutorial.

2023-04-25 14:55 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +It is also possible to start the network manually by starting first the iab-donor, then the iab-relays and finally the UE: `donor 0 start`, `iab_node start 12`, `iab_node start 34`, `iab_node start 5
I see. In general, as a user, if I try to run the command with these numbers and it does not work because the IDs are not the same anymore, I will be lost unless there is some extra info. Makes sense?

2023-04-25 14:57 UTC, gabri94 commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +It is also possible to start the network manually by starting first the iab-donor, then the iab-relays and finally the UE: `donor 0 start`, `iab_node start 12`, `iab_node start 34`, `iab_node start 5
Why the IDs should change? The toy.topology file shouldn't be changed. Anyhow if you're worried about that, we can include it in the tutorial.

2023-05-01 12:22 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +It is also possible to start the network manually by starting first the iab-donor, then the iab-relays and finally the UE: `donor 0 start`, `iab_node start 12`, `iab_node start 34`, `iab_node start 5
@gabri94

2023-05-02 23:02 UTC, mychele requested changes

2023-05-02 23:02 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +It is also possible to start the network manually by starting first the iab-donor, then the iab-relays and finally the UE: `donor 0 start`, `iab_node start 12`, `iab_node start 34`, `iab_node start 5
```suggestion
It is also possible to start the network manually by starting first the IAB-donor, then the IAB-nodes and finally the UE: `donor 0 start`, `iab_node start 12`, `iab_node start 34`, `iab_node start 56`, `iab_node start 78`, `ue 9 start`.
```

2023-05-02 23:02 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +The numbers in the commands above identify the id of the node, which is set in the topology file (`toy1.graphml`). In the case of iab-relays, since two SRNs are combined to form a single iab-relay, t
```suggestion
The numbers in the commands above identify the id of the node, which is set in the topology file (`toy1.graphml`). In the case of IAB-nodes, since two SRNs are combined to form a single IAB-node, the id is set in a separate property of the graph called `iab`. In this example is set to the union of two single ids, so if an IAB-node is made of an MT with id `1` and a DU with id `2`, its id will be `12`.
```

2023-05-02 23:02 UTC, mychele commented on _posts/tutorials/2022-02-01-iab-tutorial.md
> +This will allow iab-manager to fetch the reservations' data from the Colosseum API and automatically map the SRNs to iab-nodes of your network.
```suggestion
This will allow iab-manager to fetch the reservations' data from the Colosseum API and automatically map the SRNs to IAB-nodes of your network.
```

2023-05-02 23:02 UTC, mychele approved these changes

2023-05-02 23:06 UTC, merged