Oai gbr xapp tutorial
open-5g/openrangym pull request #12
Opened 2023-11-28 15:40 UTC by EugenioMoro

this pr is to include a tutorial on SLA management using an xapp and oai on colosseum

2023-12-01 03:34 UTC, leonardobonati commented on _data/publications.yml
> +    bibtexlink: "https://scholar.googleusercontent.com/scholar.bib?q=info:mLiNmrrMUN8J:scholar.google.com/&output=citation&scisdr=ClGyTutsEKi15M7ENgs:AFWwaeYAAAAAZWXCLgvZiaNQZCfEMz0gC92Exq0&scisig=AF
The bibtex link gives me an error.  I would suggest to use this one: https://ece.northeastern.edu/wineslab/wines_bibtex/moro2023nfv.txt

2023-12-01 03:36 UTC, leonardobonati commented on _posts/tutorials/2023-11-28-oai-o-ran-rrm-xapp.md
> +date: 2022-11-02
IIRC the page puts the tutorials in chronological order. Do you want to update the date here with a current one, matching the one in the name of the file?

2023-12-01 03:52 UTC, leonardobonati requested changes

2023-12-01 03:52 UTC, leonardobonati commented on _data/publications.yml
> +    bibtexlink: "https://scholar.googleusercontent.com/scholar.bib?q=info:mLiNmrrMUN8J:scholar.google.com/&output=citation&scisdr=ClGyTutsEKi15M7ENgs:AFWwaeYAAAAAZWXCLgvZiaNQZCfEMz0gC92Exq0&scisig=AF
Also please let's try to maintain the publication in chronological order

2023-12-11 18:34 UTC, EugenioMoro commented on _data/publications.yml
> +    bibtexlink: "https://scholar.googleusercontent.com/scholar.bib?q=info:mLiNmrrMUN8J:scholar.google.com/&output=citation&scisdr=ClGyTutsEKi15M7ENgs:AFWwaeYAAAAAZWXCLgvZiaNQZCfEMz0gC92Exq0&scisig=AF
sorry, I corrected the issue

2023-12-11 22:06 UTC, mychele commented
Let's keep the old page and have everything there, otherwise every link (from the outside) to the OAI tutorial will break @EugenioMoro

2023-12-12 13:35 UTC, leonardobonati commented on _posts/tutorials/2023-11-28-oai-o-ran-rrm-xapp.md
> +date: 2022-11-02
I would still suggest to have the filename and the date field reflecting the same date, you choose which one :)

2023-12-12 13:37 UTC, leonardobonati commented
> Let's keep the old page and have everything there, otherwise every link (from the outside) to the OAI tutorial will break @EugenioMoro

We can also put a redirect in case.

2024-03-01 08:27 UTC, EugenioMoro commented on _posts/tutorials/2023-11-28-oai-o-ran-rrm-xapp.md
> +date: 2022-11-02
I'm matching the date here with the filename

2024-03-01 08:32 UTC, EugenioMoro commented
I've fixed the date as requested by Leo, I believe it is ready now

2024-03-04 14:32 UTC, leonardobonati reviewed
Looks good to me. Should we define the acronyms `GBR` and `GTP`?

2024-03-04 14:32 UTC, leonardobonati commented on _posts/tutorials/2023-11-28-oai-o-ran-rrm-xapp.md
> +OpenAirInterface (OAI) is a 3GPP-compliant software implementation of the full 5G NR stack. In this tutorial, we show how OpenRAN Gym users can get started with deploying an OAI 5G NR SA network comp
Should we define the acronym `GBR`?

2024-03-04 14:32 UTC, leonardobonati commented on _posts/tutorials/2023-11-28-oai-o-ran-rrm-xapp.md
> +and take note of the UE GTP endpoint IP:
Should we define the acronym `GTP`?

2024-03-04 17:20 UTC, EugenioMoro commented on _posts/tutorials/2023-11-28-oai-o-ran-rrm-xapp.md
> +OpenAirInterface (OAI) is a 3GPP-compliant software implementation of the full 5G NR stack. In this tutorial, we show how OpenRAN Gym users can get started with deploying an OAI 5G NR SA network comp
Done, I've also defined SLA

2024-03-04 17:21 UTC, EugenioMoro commented on _posts/tutorials/2023-11-28-oai-o-ran-rrm-xapp.md
> +and take note of the UE GTP endpoint IP:
Done

2024-03-04 23:56 UTC, leonardobonati commented
Thanks, ok to merge. @mychele?

2024-03-04 23:57 UTC, leonardobonati approved these changes

2024-03-06 13:54 UTC, mychele commented
LGTM, at some point we should update with the new OAI images as these ones will not work well on the updated SRNs.

2024-03-08 13:17 UTC, merged