added ns-o-ran-grafana tutorial
open-5g/openrangym pull request #13
Opened 2024-02-26 15:57 UTC by CogSP

Addition of a new tutorial about [ns-o-ran-grafana](https://github.com/wineslab/ns-o-ran-grafana).

I added a new markdown file, following as much 
possible the style of the other tutorials and some images in assets/post-assets/

2024-02-26 16:22 UTC, Thecave3 commented
I will check it on my version and make a review there

2024-02-26 18:15 UTC, leonardobonati commented
Thank you for adding this tutorial. Please double-check for typos.

2024-03-02 19:51 UTC, Thecave3 requested changes
The tutorial is fine, but I would check a little bit better the language.

2024-03-02 19:51 UTC, Thecave3 commented on _posts/tutorials/2024-02-25-ns-o-ran-grafana.md
> +date: 2022-02-25
```suggestion
date: 2024-02-25
```

2024-03-02 19:51 UTC, Thecave3 commented on _posts/tutorials/2024-02-25-ns-o-ran-grafana.md
> +title: "Graphical Visualization of simulated ns-3 data with Grafana"
```suggestion
title: "Graphical Visualization of ns-O-RAN data with Grafana"
```

2024-03-02 19:51 UTC, Thecave3 commented on _posts/tutorials/2024-02-25-ns-o-ran-grafana.md
> +This script is a watchdog that monitors the output files of the ns3 simulation within the directory. The data generated by ns3 is analyzed and sent via Telegraf to InfluxDB, from which Grafana extrac
```suggestion
This script is a watchdog that monitors the output files of the ns-3 simulation within the directory. The data generated by ns-3 is collected and sent to InfluxDB through Telegraf, which is then pulled by Grafana for visualization. 
```

2024-03-02 19:51 UTC, Thecave3 commented on _posts/tutorials/2024-02-25-ns-o-ran-grafana.md
> +Four dashboard are available to be displayed:
```suggestion
Four dashboards are available:
```

2024-03-02 19:51 UTC, Thecave3 commented on _posts/tutorials/2024-02-25-ns-o-ran-grafana.md
> +In Grafana, go to 'Dashboard' then 'Manage'.
Rewrite the introduction

2024-03-04 08:27 UTC, CogSP commented on _posts/tutorials/2024-02-25-ns-o-ran-grafana.md
> +In Grafana, go to 'Dashboard' then 'Manage'.
Do you mean this part?

"This tutorial demonstrates the process of visualizing ns-3 simulation data through Grafana. The following example involve extracting data from an ns-3 simulation and transmitting it to an InfluxDB server using Telegraf, in order for Grafana to collect and present the data on a dashboard, facilitating convenient analysis and interpretation. Four distinct dashboards have been designed to showcase the data derived from “cu-up,” “cu-cp,” and “du” files within the simulation container. The fourth dashboard specifically plots aggregated data points of interest. All the code is available in [this repository](https://github.com/wineslab/ns-o-ran-grafana)."

2024-03-04 16:33 UTC, CogSP commented on _posts/tutorials/2024-02-25-ns-o-ran-grafana.md
> +In Grafana, go to 'Dashboard' then 'Manage'.
I think this is better:

"This tutorial illustrates how to visualize ns-O-RAN simulation data using Grafana. The presented example extracts information from an ns-3 simulation, sending it to InfluxDB through Telegraf. This process enables Grafana to pull and display the data on a dashboard, streamlining analysis and interpretation. Four dashboards were created, with three specifically designed to visualize data extracted from the simulation's "cu-up," "cu-cp," and "du" files. The fourth dashboard is dedicated to plotting aggregated points of interest. All the code is available in [this repository](https://github.com/wineslab/ns-o-ran-grafana)."

2024-03-04 17:18 UTC, Thecave3 commented on _posts/tutorials/2024-02-25-ns-o-ran-grafana.md
> +In Grafana, go to 'Dashboard' then 'Manage'.
Better, thanks implement this

2024-03-04 17:57 UTC, Thecave3 approved these changes

2024-03-04 17:58 UTC, merged