Added OAI RAN tutorial
open-5g/openrangym pull request #14
Opened 2024-04-24 23:57 UTC by saki92

This PR contain only the .md page. More changes needed on the framework side to show the link on the main page.

2024-04-25 03:07 UTC, Thecave3 commented
If this follows the standard layout (as it looks like) no additional code is needed to show the tutorial in the correct part.

@mychele @leonardobonati any reason why we need a link on the main page of this tutorial? 

Eventually, I can take care of it

2024-04-25 03:19 UTC, Thecave3 requested changes
I left some comments to improve the readability of the tutorial.

Is it possible to add some pictures to each step?

2024-04-25 03:19 UTC, Thecave3 commented on _posts/tutorials/2024-04-24-oai-tutorial.md
> +There are readymade images in Colosseum NAS that contains OAI RAN and 5G Core-network. These images can be selected in the Colosseum reservation page under `common` section. The images of interest ar
```suggestion
There are ready-made images in Colosseum NAS which include OAI RAN and 5G Core Network. These images can be selected in the Colosseum reservation page under the `common` section. The images of interest are
```

2024-04-25 03:19 UTC, Thecave3 commented on _posts/tutorials/2024-04-24-oai-tutorial.md
> +The OAI version in the RAN image can be updated to the current latest one by following the below mentioned instructions. This step optional and required only when needed to update or change the OAI t
```suggestion
The OAI version in the RAN image can be updated to the latest version by following the instructions below. This step is optional and only required if you need to update or change the OAI to a specific `develop` version.
```

2024-04-25 03:19 UTC, Thecave3 commented on _posts/tutorials/2024-04-24-oai-tutorial.md
> +The image contains a python tool to start the gNB  and UE.
```suggestion
The image contains a python script to start the gNB and UE.
```

2024-04-25 03:19 UTC, Thecave3 commented on _posts/tutorials/2024-04-24-oai-tutorial.md
> +This will start the gNB process. If you encounter an error related to FPGA compatibility number mismatch, then run the above command with `-f` option. This will flash the FPGA in USRP with the versio
```suggestion
This will start the gNB process. If you get an error related to FPGA compatibility number mismatch, then run the above command with `-f` option. This will flash the FPGA in USRP with the version that matches the UHD driver. This option is only needed once. The subsequent runs can be started without `-f`.
```

2024-04-25 03:19 UTC, Thecave3 commented on _posts/tutorials/2024-04-24-oai-tutorial.md
> +Now, we need to tell the MCHEM  (Massive CHannel EMulator) to setup a channel between all the nodes in the current reservation. This can be done from any one of the SRN in the reservation. The follow
```suggestion
Now we need to tell the MCHEM (Massive CHannel EMulator) to set up a channel between all the nodes in the current reservation. This can be done from any of the SRNs in the reservation. The following command starts an RF scenario with 0 dB path loss.
```

2024-04-25 03:19 UTC, Thecave3 commented on _posts/tutorials/2024-04-24-oai-tutorial.md
> +If everything goes well, then the UE should get connected to the gNB and the core-network should have assigned an IP address to the UE. This can be verified by running `ifconfig` in UE side and check
```suggestion
If all goes well, the UE should be connected to the gNB and the core network should have assigned an IP address to the UE. This can be verified by running `ifconfig` on the UE side and checking if the network interface named `oaitun_ue` has an IP assigned.
```

2024-04-25 03:19 UTC, Thecave3 commented on _posts/tutorials/2024-04-24-oai-tutorial.md
> +Sometimes, the UE might continuously fail the Random Access (RA) procedure and would not proceed beyond that point. If that happens, try changing (increase or decrease with steps of 5) the `timing_ad
```suggestion
Sometimes the UE may continuously fail the Random Access (RA) procedure and not proceed beyond that point. If this happens, try changing the `timing_advance` value in the `106` PRB section of the `conf.json` file (increase or decrease in steps of 5).
```

2024-04-25 03:19 UTC, Thecave3 commented on _posts/tutorials/2024-04-24-oai-tutorial.md
> +Ping the core-network from UE using `ping 192.168.70.135 -I oaitun_ue`. If the ping is successful, then we confirm that there is end-to-end connection between UE and 5G core-network. The user can pus
```suggestion
Ping the core-network from UE using `ping 192.168.70.135 -I oaitun_ue`. If the ping is successful, it means an end-to-end connection between the UE and the 5G core network. has been established. 
The user can push more traffic over the RAN using `iperf3` tool.
```

2024-04-25 12:09 UTC, leonardobonati commented
> If this follows the standard layout (as it looks like) no additional code is needed to show the tutorial in the correct part.
> 
> @mychele @leonardobonati any reason why we need a link on the main page of this tutorial?
> 
> Eventually, I can take care of it

The idea was to move the tutorial from our internal Confluence to the public domain, so people can access it without being added to Confluence.

2024-04-25 12:48 UTC, Thecave3 commented
> The link should be in the `Tutorials` page (and I see it already shows there), and not in the `Homepage`

Hence, we can finish the review and push the changes in the main branch.

2024-04-25 12:55 UTC, leonardobonati commented on _posts/tutorials/2024-04-24-oai-tutorial.md
> +There are readymade images in Colosseum NAS that contains OAI RAN and 5G Core-network. These images can be selected in the Colosseum reservation page under `common` section. The images of interest ar
```suggestion
There are ready-made images in Colosseum, which include OAI RAN and 5G Core Network. These images can be selected in the `common` image section of the Colosseum reservation page. The images of interest are
```

2024-04-25 12:59 UTC, leonardobonati commented on _posts/tutorials/2024-04-24-oai-tutorial.md
> +This will start the gNB process. If you encounter an error related to FPGA compatibility number mismatch, then run the above command with `-f` option. This will flash the FPGA in USRP with the versio
```suggestion
This will start the gNB process. If you get an error related to FPGA compatibility number mismatch, run the above command with `-f` option. This will flash the FPGA of the USRP with the version that matches your version of the UHD driver. This option is only needed once. The subsequent runs can be started without `-f`.
```

2024-04-25 13:00 UTC, leonardobonati commented on _posts/tutorials/2024-04-24-oai-tutorial.md
> +Now, we need to tell the MCHEM  (Massive CHannel EMulator) to setup a channel between all the nodes in the current reservation. This can be done from any one of the SRN in the reservation. The follow
```suggestion
Now we need to tell the MCHEM (Massive CHannel EMulator) to set up a channel between all the nodes in the current reservation. This can be done from any of the SRNs in the reservation. The following command starts an RF scenario with 0 dB path loss. (Please note that losses due to hardware impairments are still present.)
```

2024-04-25 13:03 UTC, leonardobonati commented on _posts/tutorials/2024-04-24-oai-tutorial.md
> +If everything goes well, then the UE should get connected to the gNB and the core-network should have assigned an IP address to the UE. This can be verified by running `ifconfig` in UE side and check
```suggestion
If all goes well, the UE should connect to the gNB and the core network should have assigned an IP address to the UE. This can be verified by running `ifconfig` on the UE side and checking if the network interface named `oaitun_ue` has an IP assigned.
```

2024-04-25 13:06 UTC, leonardobonati requested changes
Thank you for taking care of this. I added some additional suggestions.

2024-04-25 14:58 UTC, leonardobonati commented on _posts/tutorials/2024-04-24-oai-tutorial.md
> +cd OAI-Colosseum\
```suggestion
cd OAI-Colosseum
```

2024-04-25 14:59 UTC, leonardobonati commented on _posts/tutorials/2024-04-24-oai-tutorial.md
> +cd OAI-Colosseum\
```suggestion
cd OAI-Colosseum
```

2024-04-25 18:33 UTC, saki92 commented
> Is it possible to add some pictures to each step?

Do you mean screenshots?

2024-04-25 18:51 UTC, saki92 commented
@leonardobonati I changed the password of the core image to be consistent with the RAN image. Can you copy it to common section? `sakthi-cn5g-2204` -> `oai-5gcore-2024`

2024-04-25 20:20 UTC, Thecave3 commented
> > Is it possible to add some pictures to each step?
> 
> Do you mean screenshots?

Yes, it would surely help the reader to understand better the various steps and number of terminals

2024-04-25 20:21 UTC, Thecave3 approved these changes

2024-04-29 16:57 UTC, merged

2024-04-29 16:57 UTC, Thecave3 commented
Thanks, @leonardobonati can you update the website?

2024-04-29 16:59 UTC, leonardobonati commented
The website should self-update if you merge.

2024-04-29 16:59 UTC, leonardobonati commented
https://openrangym.com/tutorials/oai-tutorial