X5G tutorial kpm xapp
open-5g/openrangym pull request #15
Opened 2024-05-18 00:10 UTC by freebacca

Added KPM-xApp tutorial on X5G.

2024-05-18 00:19 UTC, freebacca commented
Links for ARC V1.2 to be fixed (pages are unreachable lately).
I will also add a placeholder for X5G in the Platform page.

2024-05-18 00:20 UTC, mychele requested changes
Thanks @freebacca, some suggestions on the language

2024-05-18 00:20 UTC, mychele commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +title: "KPM xApp with OSC Near-RT RIC and X5G"
```suggestion
title: "KPM xApp with the OSC Near-RT RIC and NVIDIA ARC on X5G"
```

2024-05-18 00:20 UTC, mychele commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +short-description: How to run a KPM xApp leveraging the X5G testbed comprising OAI, NVIDIA ARC-OTA, and OSC Near-RT RIC
```suggestion
short-description: How to run a KPM xApp leveraging the X5G testbed comprising OAI, NVIDIA ARC-OTA, and the OSC Near-RT RIC
```

2024-05-18 00:20 UTC, mychele commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +[X5G](https://x5g.org/) comprises of an open, programmable, and multi-vendor private 5G O-RAN testbed deployed at Northeastern University, Boston, MA, USA. It features an 8-node network deployment of
```suggestion
[X5G](https://x5g.org/) comprises of an open, programmable, and multi-vendor private 5G O-RAN testbed deployed at Northeastern University, Boston, MA, USA. It features an 8-node network deployment of the [NVIDIA Aerial RAN CoLab Over-The-Air (ARC-OTA)](https://docs.nvidia.com/aerial/aerial-ran-colab-ota/index.html), with [OpenAirInterface](https://openairinterface.org/) for the higher layers, the [NVIDIA Aerial](https://docs.nvidia.com/aerial/index.html) Software Development Kit (SDK) for the High-PHY layer, accelerated on GPUs, and Radio Units (RUs) manufactured by various vendors, including Foxconn. Additionally, X5G features the O-RAN Software Community (OSC) Near-RT RIC deployed on an OpenShift cluster and integrated with an E2 agent in OAI.
```

2024-05-18 00:20 UTC, mychele commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +The O-RAN Software Community (OSC) Near-RT RIC Release E can be installed following [this guide](https://docs.o-ran-sc.org/projects/o-ran-sc-ric-plt-ric-dep/en/latest/installation-guides.html).
Is this specific to Release E?

2024-05-18 00:20 UTC, mychele commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +An OAI version with the Custom E2 Agent already integrated in the 2024w18 can be found at [this GitHub repository](https://github.com/wineslab/x5g-openairinterface/tree/2024w18_e2agent).
```suggestion
The E2 agent is based on the OSC e2sim project. An OAI version with the custom E2 Agent already integrated in the 2024w18 can be found at [this GitHub repository](https://github.com/wineslab/x5g-openairinterface/tree/2024w18_e2agent).
```

2024-05-18 00:20 UTC, mychele commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +The e2sim is a component that can run on the same machine as the OAI gNB and has the duty to encapsulate/decapsulate the custom Service Model (SM) buffers to be sent to or received from the gNB. It c
```suggestion
The e2sim is a component that can run on the same server as the OAI L2/L3 and ARC PHY and has the duty to encapsulate/decapsulate the custom Service Model (SM) buffers to be sent to or received from the gNB. It communicates with the gNB via UDP sockets. The e2sim codebase can be found at [this GitHub repository](https://github.com/wineslab/ran-e2sim/tree/x5g-e2sim).
```

2024-05-18 00:20 UTC, mychele commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +- Terminal 4 (T4): xApp connector (OpenShift xApp Pod)
```suggestion
- Terminal 4 (T4): xApp connector (xApp Container in OSC RIC)
```

2024-05-18 00:20 UTC, mychele commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +- Terminal 5 (T5): xApp Python (OpenShift xApp Pod)
```suggestion
- Terminal 5 (T5): xApp Python (xApp Container in OSC RIC)
```

2024-05-18 18:07 UTC, freebacca commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +The O-RAN Software Community (OSC) Near-RT RIC Release E can be installed following [this guide](https://docs.o-ran-sc.org/projects/o-ran-sc-ric-plt-ric-dep/en/latest/installation-guides.html).
It is a general guide, you then specify the version during the installation.

2024-05-18 21:38 UTC, leonardobonati requested changes
Thank you for working on this. Please fix or remove broken links. Thank you

2024-05-18 21:38 UTC, leonardobonati commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +[X5G](https://x5g.org/) comprises of an open, programmable, and multi-vendor private 5G O-RAN testbed deployed at Northeastern University, Boston, MA, USA. It features an 8-node network deployment of
This page does not exist

2024-05-18 21:38 UTC, leonardobonati commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +The NVIDIA Aerial RAN CoLab Over-the-Air (ARC-OTA) information can be found at [this website](https://docs.nvidia.com/aerial/aerial-ran-colab-ota/index.html).
This page does not exist

2024-05-18 21:38 UTC, leonardobonati commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +In T1, we first run the `NVIDIA L1 cuBB`, for example, by using the following command (it may vary based on your ARC release and configurations, please refer to [ARC-OTA 1.2](https://docs.nvidia.com/
This page does not exist

2024-05-18 21:40 UTC, leonardobonati commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +The O-RAN Software Community (OSC) Near-RT RIC Release E can be installed following [this guide](https://docs.o-ran-sc.org/projects/o-ran-sc-ric-plt-ric-dep/en/latest/installation-guides.html).
k8s has networking issues when reaching e2term from external systems (at lease on this release of the RIC). Does it make sense to emphasize that we are running this on OpenShift?

2024-05-18 23:03 UTC, freebacca commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +In T1, we first run the `NVIDIA L1 cuBB`, for example, by using the following command (it may vary based on your ARC release and configurations, please refer to [ARC-OTA 1.2](https://docs.nvidia.com/
Fixed.

2024-05-18 23:03 UTC, freebacca commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +The NVIDIA Aerial RAN CoLab Over-the-Air (ARC-OTA) information can be found at [this website](https://docs.nvidia.com/aerial/aerial-ran-colab-ota/index.html).
This one should exist. Will be brought up soon probably (I'll keep an eye).

2024-05-18 23:06 UTC, freebacca commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +The NVIDIA Aerial RAN CoLab Over-the-Air (ARC-OTA) information can be found at [this website](https://docs.nvidia.com/aerial/aerial-ran-colab-ota/index.html).
Fixed.

2024-05-18 23:06 UTC, freebacca commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +[X5G](https://x5g.org/) comprises of an open, programmable, and multi-vendor private 5G O-RAN testbed deployed at Northeastern University, Boston, MA, USA. It features an 8-node network deployment of
This link should exist. I'll keep an eye on it.

2024-05-19 00:20 UTC, leonardobonati commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +The NVIDIA Aerial RAN CoLab Over-the-Air (ARC-OTA) information can be found at [this website](https://docs.nvidia.com/aerial/aerial-ran-colab-ota/index.html).
It still cannot be found

2024-05-19 00:20 UTC, leonardobonati commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +In T1, we first run the `NVIDIA L1 cuBB`, for example, by using the following command (it may vary based on your ARC release and configurations, please refer to [ARC-OTA 1.2](https://docs.nvidia.com/
It still cannot be found

2024-05-19 00:22 UTC, leonardobonati commented
> I will also add a placeholder for X5G in the Platform page.

I would break the tutorial in two pages: the first one in the platforms section, and the second one as the tutorial page

2024-05-19 00:22 UTC, freebacca commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +In T1, we first run the `NVIDIA L1 cuBB`, for example, by using the following command (it may vary based on your ARC release and configurations, please refer to [ARC-OTA 1.2](https://docs.nvidia.com/
Check the latest commit. This now is: https://docs.nvidia.com/aerial/cuda-accelerated-ran/aerial_cubb/cubb_quickstart/running_cubb-end-to-end.html

2024-05-19 00:23 UTC, freebacca commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +The NVIDIA Aerial RAN CoLab Over-the-Air (ARC-OTA) information can be found at [this website](https://docs.nvidia.com/aerial/aerial-ran-colab-ota/index.html).
Check the latest commit, this now is: https://docs.nvidia.com/aerial/cuda-accelerated-ran/index.html

2024-05-19 00:24 UTC, freebacca commented
> > I will also add a placeholder for X5G in the Platform page.
> 
> I would break the tutorial in two pages: the first one in the platforms section, and the second one as the tutorial page

I meant to add X5G in the platform section of the website, not in this tutorial.

2024-05-19 00:24 UTC, leonardobonati commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +The NVIDIA Aerial RAN CoLab Over-the-Air (ARC-OTA) information can be found at [this website](https://docs.nvidia.com/aerial/aerial-ran-colab-ota/index.html).
Thanks, it was still showing the old code snipped above

2024-05-19 00:24 UTC, leonardobonati commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +In T1, we first run the `NVIDIA L1 cuBB`, for example, by using the following command (it may vary based on your ARC release and configurations, please refer to [ARC-OTA 1.2](https://docs.nvidia.com/
Thanks, it was still showing the old code snipped above

2024-05-20 16:12 UTC, Thecave3 requested changes
Try to remove the articles from the links. I would emphasize the Open RAN language in general.

Are the final link actually useful? They point to tutorials while usually you may want them to point them on the general product page.

2024-05-20 16:12 UTC, Thecave3 commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +> {{ pub_villa2024x5g | strip_newlines }}
Unrelated to this PR, but let's maybe open an issue.
The new UI for publication does not highlight it well and should open the links in a blank page instead of substituting the actual one.

@leonardobonati where is the source code for the style of this? There are some issues that need an hotfix

2024-05-20 16:12 UTC, Thecave3 commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +The NVIDIA Aerial information and installation guide is available at [this website](https://docs.nvidia.com/aerial/cuda-accelerated-ran/index.html).
```suggestion
The NVIDIA Aerial information and installation guide is available at this [website](https://docs.nvidia.com/aerial/cuda-accelerated-ran/index.html).
```
```suggestion
The NVIDIA Aerial information and installation guide is available at [this website](https://docs.nvidia.com/aerial/cuda-accelerated-ran/index.html).
```

2024-05-20 16:12 UTC, Thecave3 commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +A basic xApp developed in Python and easily extendable can be found at [this GitHub repository](https://github.com/wineslab/xapp-oai/tree/kpm-xapp). This repository contains a few Python examples tha
```suggestion
A basic and easily extensible xApp developed in Python can be found at the [GitHub repository](https://github.com/wineslab/xapp-oai/tree/kpm-xapp). This repository contains some Python examples that can subscribe to selected RAN parameters, receive periodic indication messages, and send control requests to update these parameters.
```
```suggestion
A basic xApp developed in Python and easily extendable can be found at [this GitHub repository](https://github.com/wineslab/xapp-oai/tree/kpm-xapp). This repository contains a few Python examples that can subscribe to selected RAN parameters, receive periodic indication messages, and send control requests to update these parameters.
```

2024-05-20 17:55 UTC, freebacca commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +The NVIDIA Aerial information and installation guide is available at [this website](https://docs.nvidia.com/aerial/cuda-accelerated-ran/index.html).
I would prefer to keep [this website] to be consistent with the rest.

2024-05-20 17:56 UTC, freebacca commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +> {{ pub_villa2024x5g | strip_newlines }}
Which articles and links are you referring to in particular that you think it is better to remove?

2024-05-20 18:09 UTC, freebacca commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +[X5G](https://x5g.org/) comprises of an open, programmable, and multi-vendor private 5G O-RAN testbed deployed at Northeastern University, Boston, MA, USA. It features an 8-node network deployment of
It still doesn't exist. I will merge and tell Anupa that it is not available.

2024-05-20 18:14 UTC, freebacca commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +> {{ pub_villa2024x5g | strip_newlines }}
I will add an overview of X5G in the Platform tab of the website. Here is mostly to give people useful pointers to run the demo.

2024-05-20 18:47 UTC, leonardobonati commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +[X5G](https://x5g.org/) comprises of an open, programmable, and multi-vendor private 5G O-RAN testbed deployed at Northeastern University, Boston, MA, USA. It features an 8-node network deployment of
Please remove the link if it does not exist. You can add it at a later stage

2024-05-20 18:50 UTC, Thecave3 commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +> {{ pub_villa2024x5g | strip_newlines }}
Everything that is not strictly related to the tutorial must be removed and put on the aforementioned page.

2024-05-20 18:50 UTC, freebacca commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +[X5G](https://x5g.org/) comprises of an open, programmable, and multi-vendor private 5G O-RAN testbed deployed at Northeastern University, Boston, MA, USA. It features an 8-node network deployment of
Link removed for now.

2024-05-20 18:59 UTC, Thecave3 commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +The NVIDIA Aerial information and installation guide is available at [this website](https://docs.nvidia.com/aerial/cuda-accelerated-ran/index.html).
`this` in general is ugly in this context.

```suggestion
The NVIDIA Aerial information and installation guide is available at the [official website](https://docs.nvidia.com/aerial/cuda-accelerated-ran/index.html).
```

2024-05-20 19:09 UTC, freebacca commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +> {{ pub_villa2024x5g | strip_newlines }}
Added the X5G page in the platform tab.

2024-05-20 19:09 UTC, freebacca commented on _posts/tutorials/2024-05-18-x5g-kpm-xapp.md
> +The NVIDIA Aerial information and installation guide is available at [this website](https://docs.nvidia.com/aerial/cuda-accelerated-ran/index.html).
Ok, fixed!

2024-05-20 19:19 UTC, Thecave3 approved these changes

2024-05-20 19:21 UTC, merged