Added xDevSM tutorial
open-5g/openrangym pull request #18
Opened 2024-09-22 14:17 UTC by aferaudo

### xDevSM tutorial

@Thecave3 Missing paper reference: it will be added once published.

2024-09-22 19:33 UTC, mychele requested changes
I would add a couple of examples at the end of how you use it with OAI and srs, thoughts?

2024-09-22 19:33 UTC, mychele commented on _posts/tutorials/2024-09-16-xdevsm-tutorial.md
> +title: "Deploying an xDevSM-Based xApp with OSC NearRT-RIC"
```suggestion
title: "Deploying an xDevSM-Based xApp with the OSC NearRT-RIC"

```

2024-09-22 19:33 UTC, mychele commented on _posts/tutorials/2024-09-16-xdevsm-tutorial.md
> +These tools are necessary for building and creating Helm charts for your xApp.
Any specific version of helm and docker? I would also link to the guide to deploy the OSC RIC, just to give credits to the part below

2024-09-22 19:33 UTC, mychele commented on _posts/tutorials/2024-09-16-xdevsm-tutorial.md
> +> Note: Details about why we are using ```flexric``` can be found in the paper.
Remember to add link later

2024-09-23 08:23 UTC, aferaudo commented on _posts/tutorials/2024-09-16-xdevsm-tutorial.md
> +These tools are necessary for building and creating Helm charts for your xApp.
I'll add just the helm version.

I'll also include the link to the official OSC RIC deployment procedure.

2024-09-23 08:30 UTC, aferaudo commented
It's just a matter of configuration on the SRS side.
About OAI,  I can provide the guide for building the gNB with the E2 Agent and instructions on how to modify the configuration file to enable the connection with the near-RT RIC.

Should we include anything else?

2024-09-23 14:04 UTC, Thecave3 commented
Does it make sense to have the page in the O-RAN framework as well?

2024-09-23 16:20 UTC, aferaudo commented
That makes sense to me. I would focus on the tutorial for this PR and add the framework later if you agree.

2024-09-23 16:43 UTC, leonardobonati commented on _posts/tutorials/2024-09-16-xdevsm-tutorial.md
> +> Add paper
Does it make sense to put the paper at the end of the page, as done in ns-O-RAN, for example? (Up for discussion) https://openrangym.com/tutorials/ns-o-ran

2024-09-23 16:46 UTC, leonardobonati commented
@aferaudo if you create an entry for the paper at the end of the `publications` item in [this](https://github.com/aferaudo/openrangym/blob/main/_data/publications.yml) page, it will show in the publications page as well. Then, you can reuse the entry in the page.

2024-09-23 16:58 UTC, aferaudo commented
> @aferaudo if you create an entry for the paper at the end of the `publications` item in [this](https://github.com/aferaudo/openrangym/blob/main/_data/publications.yml) page, it will show in the publications page as well. Then, you can reuse the entry in the tutorial page.

@leonardobonati Yes, I saw that page. I didn't include it because we don’t have a link available yet. I can add an entry with random data for the `pdflink` and `bibtexlink` , we can update it once the published version is ready. Alternatively, we can upload it on arxiv and use that for now.

2024-09-23 16:59 UTC, aferaudo commented on _posts/tutorials/2024-09-16-xdevsm-tutorial.md
> +> Add paper
Yes, we can put it at the end of the page.

2024-09-23 17:04 UTC, leonardobonati commented
> > @aferaudo if you create an entry for the paper at the end of the `publications` item in [this](https://github.com/aferaudo/openrangym/blob/main/_data/publications.yml) page, it will show in the publications page as well. Then, you can reuse the entry in the tutorial page.
> 
> @leonardobonati Yes, I saw that page. I didn't include it because we don’t have a link available yet. I can add an entry with random data for the `pdflink` and `bibtexlink` , we can update it once the published version is ready. Alternatively, we can upload it on arxiv and use that for now.

You can leave it empty if you don't have it yet. Please don't add random stuff :-)

2024-09-23 21:17 UTC, mychele approved these changes
Thanks @aferaudo

2024-09-23 22:21 UTC, leonardobonati commented on _data/publications.yml
> +    pdflink: ""
```suggestion
```

2024-09-23 22:21 UTC, leonardobonati commented on _data/publications.yml
> +    bibtexlink: ""
```suggestion
```

2024-09-23 22:21 UTC, leonardobonati commented on _data/publications.yml
> +    pdflink: ""
I would just remove this if you don't have an entry yet.

2024-09-23 22:22 UTC, leonardobonati commented on _data/publications.yml
> +    bibtexlink: ""
Why don't you put this? https://ece.northeastern.edu/wineslab/wines_bibtex/feraudo2024xDevSM.txt

2024-09-23 22:23 UTC, leonardobonati approved these changes

2024-09-23 22:24 UTC, mychele approved these changes

2024-09-23 22:24 UTC, merged