New page for the commercial traffic twinning dataset
open-5g/openrangym pull request #19
Opened 2024-09-30 21:23 UTC by RavisBlue

2024-09-30 23:21 UTC, leonardobonati requested changes
Thank you for putting this together. Can you add links to the Madrid dataset, and to MGEN?

2024-09-30 23:21 UTC, leonardobonati commented on _posts/datasets/2024-09-30-open-ran-commercial-traffic-twinning-dataset.md
> +title: "Open-RAN Commercial Traffic Twinning Dataset"
```suggestion
title: "Open RAN Commercial Traffic Twinning Dataset"
```

2024-09-30 23:21 UTC, leonardobonati commented on _posts/datasets/2024-09-30-open-ran-commercial-traffic-twinning-dataset.md
> +We emulate a 5G network with 1 base station and 8 users in the dense urban scenario of Rome, Italy. We consider a multi-slice scenario in which the users are statically assigned to a slice of the net
```suggestion
We emulate a 5G network with 1 base station and 8 users in the dense urban scenario of Rome, Italy. We consider a multi-slice scenario in which the users are statically assigned to a slice of the network. The traffic they request is generated by MGEN and falls into two different traffic types: high-capacity enhanced Mobile Broadband (eMBB) for UEs 1-4 allocated to slice 0, and Ultra-reliable Low-latency Communications (URLLC) for UEs 5-8 allocated to slice 1. The traffic is twinned from real-world traces from base stations in a suburban area of Madrid, covering three different spectrum bands (816 MHz, 1835 MHz, and 2650 MHz). For the same traffic and slicing configuration, we experiment with the proportionally fair and round-robin scheduling policies. The dataset contains five different slicing configurations, each showing how the 50 PRBs (10 MHz of spectrum) are allocated between the two slices. The details are provided in the following tables.
```

2024-10-01 16:22 UTC, Thecave3 commented
Try to use markdown for links!

2024-10-01 17:22 UTC, leonardobonati approved these changes

2024-10-01 17:44 UTC, merged