Add Tutorials section on the website and tutorial on the setup of ns-O-RAN
open-5g/openrangym pull request #2
Opened 2022-11-03 22:22 UTC by Thecave3

I have implemented a new section called "Tutorials" and a new article that guides the user into the setup of ns-O-RAN with the Coloran Near RT RIC.

I would like to ask @mychele to review the ns-O-RAN tutorial content and @leonardobonati for the creation of the new section and the goodness of the new features implemented.

2022-11-03 22:32 UTC, mychele requested changes

2022-11-03 22:32 UTC, mychele commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +This part of the tutorial requires a working version of docker for hosting the RIC on your localhost.
Docker

2022-11-03 22:32 UTC, mychele commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +This part of the tutorial requires a working version of docker for hosting the RIC on your localhost.
check below too

2022-11-03 22:32 UTC, mychele commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +./setup-ric-bronze.sh # setup and launch
Why bronze?

2022-11-03 22:32 UTC, mychele commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +./setup-ric-bronze.sh # setup and launch
I just run ./setup-ric

2022-11-03 22:32 UTC, mychele commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +./setup-ric-bronze.sh # setup and launch
Does this take care of the interface?

2022-11-03 22:32 UTC, mychele commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +To understand what is going on in the RIC and to have a feedback once we will start ns-O-RAN, we can open two terminal for the RIC, one for logging the values on the E2Term and check the E2AP message
```suggestion
To understand what is going on in the RIC and to have a feedback once we start ns-O-RAN, we can open two terminal for the RIC, one for logging the values on the E2Term and check the E2AP messages exchange, the other for the xApp.
```

2022-11-03 22:32 UTC, mychele commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +- The E2-Sim, which was originally developed by the OSC community.
e2sim

2022-11-03 22:32 UTC, mychele commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +- The ns-3 Mmwave version, which was originally developed by the University of Padua and NYU.
ns3-mmWave

2022-11-03 22:32 UTC, mychele commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +- The E2-Sim, which was originally developed by the OSC community.
also below

2022-11-03 22:32 UTC, mychele commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +- The ns-3 Mmwave version, which was originally developed by the University of Padua and NYU.
also below

2022-11-03 23:17 UTC, leonardobonati approved these changes
LGTM.

2022-11-04 03:11 UTC, leonardobonati approved these changes
Changed CSS for code highlighting and table.

2022-11-04 09:22 UTC, Thecave3 commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +./setup-ric-bronze.sh # setup and launch
Yes, the only change w.r.t. the original script is that we tag the version as bronze. I can leave ./setup-ric.sh since you confirmed that was working yesterday

2022-11-04 09:42 UTC, Thecave3 commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +./setup-ric-bronze.sh # setup and launch
@mychele this is the last point. When we solve this, I am able to merge the branch .

2022-11-04 12:02 UTC, mychele commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +./setup-ric-bronze.sh # setup and launch
If you also try it locally, and it works, I would just leave setup-ric.

2022-11-04 15:38 UTC, Thecave3 commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +./setup-ric-bronze.sh # setup and launch
Local setup does not work with it because the images imported from wineslab are not tagged as `latest`. while on the docker hub they are tagged in another way.
This may cause confusion and inconsistencies among potential users. 
I would leave it as it is and plan to update it with the upcoming interoperability milestones

2022-11-04 15:40 UTC, leonardobonati commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +./setup-ric-bronze.sh # setup and launch
Can you tag the images in the right way after importing them?

2022-11-04 15:45 UTC, Thecave3 commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +./setup-ric-bronze.sh # setup and launch
Yes, but I don't want to use the tag latest to prevent overlaps between versions

2022-11-04 15:49 UTC, Thecave3 commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +./setup-ric-bronze.sh # setup and launch
The pull command is doing this operation for all the images:
`docker pull wineslab/o-ran-sc-bldr-ubuntu18-c-go:9-u18.04`
Since I am not sure about calling it latest, I saved and run it with another name (i.e., `bronze`).
I can change the script `./import-wines-images.sh` to tag them as latest, but I am not sure they are the same version on the RIC on Colosseum

2022-11-04 19:51 UTC, mychele commented on _posts/tutorials/2022-02-11-ns-o-ran.md
> +./setup-ric-bronze.sh # setup and launch
I am going to merge this and then we can further discuss

2022-11-04 19:54 UTC, mychele approved these changes

2022-11-04 19:54 UTC, merged